# Generated by Django 5.1.6 on 2026-01-26 16:40

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_date_joined_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes', verbose_name='File Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(default=0, help_text='Sanitized original filename', max_length=255, verbose_name='Original Filename'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=chat.models.secure_upload_path, verbose_name='File'),
        ),
    ]
